# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstSeminar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirstSeminar
  pod 'FSCalendar'

  target 'FirstSeminarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirstSeminarUITests' do
    # Pods for testing
  end

end
